apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher
  labels:
    app: rancher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher
  template:
    metadata:
      labels:
        app: rancher
    spec:
      containers:
      - name: rancher
        image: rancher/rancher:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rancher-service
spec:
  selector:
    app: rancher
  ports:
    - protocol: TCP
      port: 80     
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
name: rancher-ingress
annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
rules:
- host: "rancher.jpconstantineau.com"
  - http:
    paths:
    - path: /
        backend:
        serviceName: rancher-service
        servicePort: 80    