apiVersion: v1
kind: PersistentVolume
metadata:
  name: xenorchestra-redis-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /Pool/KubeVolumes/xenorchestra-redis
    server: 192.168.1.192
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: xenorchestra-redis-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: xenorchestra-xo-server-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /Pool/KubeVolumes/xenorchestra-xo-server
    server: 192.168.1.192
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: xenorchestra-xo-server-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xenorchestra-redis-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xenorchestra-xo-server-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xenorchestra-deployment
  labels:
    app: xenorchestra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xenorchestra
  template:
    metadata:
      labels:
        app: xenorchestra
    spec:
      containers:
      - name: xenorchestra
        image: ronivay/xen-orchestra
        ports:
        - containerPort: 80
        volumeMounts:
        - name: xenorchestra-xo-server
          mountPath: /var/lib/xo-server
        - name: xenorchestra-redis
          mountPath: /var/lib/redis
      volumes:
      - name: xenorchestra-redis
        persistentVolumeClaim:
          claimName: xenorchestra-redis-pv-claim
      - name: xenorchestra-xo-server
        persistentVolumeClaim:
          claimName: xenorchestra-xo-server-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: xenorchestra-service
spec:
  selector:
    app: xenorchestra
  ports:
    - protocol: TCP
      port: 80
      name: http         
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: xenorchestra-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: "xenorchestra.jpconstantineau.com"
    http:
      paths:
        - path: /
          backend:
            serviceName: xenorchestra-service
            servicePort: 80  