apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argocd-server-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: "cicd.jpconstantineau.com"
    http:
      paths:
      - path: /
        backend:
          serviceName: argocd-server
          servicePort: 80           