apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall-deployment
  labels:
    app: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
      - name: heimdall
        image: linuxserver/heimdall
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: heimdall-service
spec:
  selector:
    app: heimdall
  ports:
    - protocol: TCP
      port: 80 
    - protocol: TCP
      port: 443          
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: heimdall-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: "menu.jpconstantineau.com"
    http:
      paths:
        - path: /
          backend:
            serviceName: heimdall-service
            servicePort: 80  