apiVersion: v1
kind: PersistentVolume
metadata:
  name: heimdall-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /Pool/KubeVolumes/heimdall
    server: 192.168.1.192
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: heimdall-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall-deployment
  labels:
    app: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
      - name: heimdall
        image: linuxserver/heimdall:version-2.2.2
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: heimdall-data
          mountPath: /config
      volumes:
      - name: heimdall-data
        persistentVolumeClaim:
          claimName: heimdall-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: heimdall-service
spec:
  selector:
    app: heimdall
  ports:
    - protocol: TCP
      port: 80
      name: http 
    - protocol: TCP
      port: 443  
      name: https        
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: heimdall-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: "menu.jpconstantineau.com"
    http:
      paths:
        - path: /
          backend:
            serviceName: heimdall-service
            servicePort: 80 