apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-deployment
  labels:
    app: mosquitto
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      hostNetwork: true
      nodeSelector:
        k3s.io/hostname: k3s-2
      containers:
      - name: mosquitto
        image: eclipse-mosquitto
        resources:
          limits:
            cpu: 1
            memory: 500Mi
        volumeMounts:
        - name: mosquitto-config
          mountPath: /mosquitto/config/
        - name: localtime
          mountPath: /etc/localtime
        - name: mosquitto-data
          mountPath: /mosquitto/data
        - name: mosquitto-log
          mountPath: /mosquitto/log
      volumes:
      - name: mosquitto-config
        persistentVolumeClaim:
          claimName: mosquitto-config-pvc
      - name: mosquitto-data
        persistentVolumeClaim:
          claimName: mosquitto-data-pvc
      - name: mosquitto-log
        persistentVolumeClaim:
          claimName: mosquitto-log-pvc
      - name: localtime
        hostPath:
          path: /etc/localtime
---
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: mosquitto-config-pv
  spec:
    capacity:
      storage: 15Mi
    accessModes:
      - ReadOnlyMany
    nfs:
      path: /Pool/KubeVolumes/mosquitto-config
      server: 192.168.1.192
      claimRef:
    persistentVolumeReclaimPolicy: Retain
    claimRef:
      namespace: default
      name: mosquitto-config-pvc
---
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: mosquitto-data-pv
  spec:
    capacity:
      storage: 50Mi
    accessModes:
      - ReadWriteOnce
    nfs:
      path: /Pool/KubeVolumes/mosquitto-data
      server: 192.168.1.192
    persistentVolumeReclaimPolicy: Retain
    claimRef:
      namespace: default
      name: mosquitto-data-pvc
---
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: mosquitto-log-pv
  spec:
    capacity:
      storage: 25Mi
    accessModes:
      - ReadWriteOnce
    nfs:
      path: /Pool/KubeVolumes/mosquitto-log
      server: 192.168.1.192
    persistentVolumeReclaimPolicy: Retain
    claimRef:
      namespace: default
      name: mosquitto-log-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquitto-config-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 15Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquitto-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquitto-log-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Mi