apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /Pool/KubeVolumes/home-assistant
    server: storage
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: home-assistant-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi