apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /Pool/KubeVolumes/home-assistant
    server: 192.168.1.192
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: home-assistant-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant-deployment
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      hostNetwork: true
      nodeSelector:
        hostname: k3s-2
      containers:
      - name: home-assistant
        image: homeassistant/home-assistant:stable
        resources:
          limits:
            cpu: 1
            memory: 500Mi
        volumeMounts:
        - name: home-assistant-data
          mountPath: /config
        env:
        - name: TZ
          value: America/Regina
        ports:
        - containerPort: 8123
      volumes:
      - name: home-assistant-data
        persistentVolumeClaim:
          claimName: home-assistant-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-service
  namespace: default
spec:
  selector:
    app: home-assistant
  ports:
    - protocol: TCP
      port: 8123
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: home-assistant-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: "home-assistant.jpconstantineau.com"
    http:
      paths:
        - path: /
          backend:
            serviceName: home-assistant-service
            servicePort: 8123 