apiVersion: v1
kind: PersistentVolume
metadata:
  name: esphome-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /Pool/KubeVolumes/esphome
    server: 192.168.1.192
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: esphome-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esphome-deployment
  labels:
    app: esphome
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: esphome
  template:
    metadata:
      labels:
        app: esphome
    spec:
      hostNetwork: true
      nodeSelector:
        k3s.io/hostname: k3s-2
      containers:
      - name: esphome
        image: esphome/esphome
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            cpu: 1
            memory: 500Mi
        volumeMounts:
        - name: esphome-data
          mountPath: /config
        ports:
        - containerPort: 6052
      volumes:
      - name: esphome-data
        persistentVolumeClaim:
          claimName: esphome-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: esphome-service
  namespace: default
spec:
  selector:
    app: esphome
  ports:
    - protocol: TCP
      port: 6052
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: esphome-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: "esphome.jpconstantineau.com"
    http:
      paths:
        - path: /
          backend:
            serviceName: esphome-service
            servicePort: 6052 