apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /Pool/KubeVolumes/influxdb
    server: 192.168.1.192
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: influxdb-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        hostNetwork: true
        image: influxdb/influxdb
        volumeMounts:
        - name: influxdb-data
          mountPath: /var/lib/influxdb
        env:
        - name: TZ
          value: America/Regina
        ports:
        - containerPort: 8086
      volumes:
      - name: influxdb-data
        persistentVolumeClaim:
          claimName: influxdb-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: default
spec:
  selector:
    app: influxdb
  ports:
    - protocol: TCP
      port: 8086
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: influxdb-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: "influxdb.jpconstantineau.com"
    http:
      paths:
        - path: /
          backend:
            serviceName: influxdb-service
            servicePort: 8086 